apiVersion: v1
kind: ConfigMap
metadata: 
  name: redmine-configmap
data:
  DATABASE_NAME: redmine
  DATABASE_HOST: postgres-service
  RAILS_ENV: production
  SECRET_KEY_BASE: yqvcCgsQQC+Rq/n6

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: redmine
  POSTGRES_USER: rails
  POSTGRES_PASSWORD: redmine123
  